name: Build and Push Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Checkout all history for GitVersion to be able to calculate the version

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.5.0'

      - name: Determine Version
        id: gitversion # id to later be referenced
        uses: gittools/actions/gitversion/execute@v0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${{ steps.gitversion.outputs.nuGetVersionV2 }}

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: nuget-package
          path: '**/*.nupkg'

  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Download package
        uses: actions/download-artifact@v2
        with:
          name: nuget-package
          path: ./packages

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Authenticate with GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | nuget sources add -name "github" -source https://nuget.pkg.github.com/$GITHUB_REPOSITORY_OWNER/index.json -username ${{ github.actor }} -password-stdin

      - name: Publish package
        run: dotnet nuget push "**/*.nupkg" --source "github"
